### ISSUE TITLE
Stucked with AI Assist button with disabled app

### ISSUE THREAD

**Issue by manzing** [RocketChat/ChatGPT-for-Rocket.Chat#8]
Hello,

I tried the app but it doesn't work as expected. I disabled it but the "AI Assist" button remains in clients.
Even if I uninstall the app the button is still there and displays a not found windows when clicking on it.
Sadly, we use GridFS so I cannot remove app files directly from the filesystem.
Is there any way to get rid of it?

![image](https://github.com/RocketChat/ChatGPT-for-Rocket.Chat/assets/2737265/3c2ef932-d5dd-4c2d-8869-194f5521bca9)

Thanks,

**Comment by murtaza98** [comment]
Hello @manzing You'll need to clear the custom javascript scripts added by this app on your server to hide this button. You can find the setting here (Admin -> Settings -> Layout -> Custom Scripts)
![image](https://github.com/RocketChat/ChatGPT-for-Rocket.Chat/assets/34130764/a2fd834b-8776-4bc0-b2d6-ad36a18ccca4)

**Comment by murtaza98** [comment]
I agree, this should be somehow automated but I couldn't find a way to achieve this via apps-engine. In-case you're familiar with it and have a solution, then do let me know :)
